update

diff --git a/scripts/configure b/scripts/configure
--- a/scripts/configure
+++ b/scripts/configure
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 
 CONFIG_FILE=".env"
+
+if [ ! -f $CONFIG_FILE ]; then
+    echo "Error: Configuration file '$CONFIG_FILE' not found."
+    echo "Run 'scripts/configure' to configure your module."
+    exit 1
+fi
+
 source $CONFIG_FILE
 
 if [[ -z $MODEL_NAME ]]; then
